version: "3"

services:
  # Discord bot
  discord-bot:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: "ghcr.io/dutchdronesquad/dds-bot:latest"
    container_name: DDS-Bot-Dev
    environment:
      TOKEN: ${BOT_TOKEN}
    restart: unless-stopped