version: "3"

services:
  # Discord bot
  discord:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DDS-Bot-Dev
    environment:
      TOKEN: ${BOT_DEV_TOKEN}
    restart: unless-stopped